a=int(input("English"))
b=int(input("Physics"))
c=int(input("dhemistry"))
d=int(input("Mathematics"))
e=int(input("Computer Science"))

fmarks=(a+b+c+d+e)
print(fmarks)
percentage=(fmarks/500*100)
print(percentage)
